version: "3.5"
services:
  customer-service:
    container_name: customer-service
    image: nzlvrsrg/customer-service:0.0.1
    depends_on:
      customer-db :
          condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:mysql://customer-db:3306/customer_db
      DB_USERNAME: root
      DB_PASSWORD: password
      KAFKA_URL: kafka:29092
    restart: always
    ports:
      - 8082:9090
    networks:
      - microservices_network
  customer-db:
    container_name: customer-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer_db
    ports:
      - 8002:3306
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    networks:
      - microservices_network

networks:
  microservices_network:
    name: microservices_network
